package com.customfit.ctg.model;

public enum GroceryCategory {
	BABY_CARE,
	BAKERY_ITEMS,
	BAKING_SUPPLIES,
	BASIC_COOKING_INGREDIENTS,
	BEVERAGES,
	CANNED_FOODS,
	CEREALS,
	CONDIMENTS_AND_SALAD_DRESSINGS,
	DAIRY_EGGS_AND_MILK,
	DELI,
	ETHNIC_FOODS,
	FROZEN_FOODS,
	HEALTH_AND_BEAUTY,
	HERBS_AND_SPICES,
	HOUSEHOLD_PRODUCTS,
	MEATS_FISH_AND_SEAFOOD,
	NATURAL_ORGANIC_FOODS,
	OTHER,
	PASTA_RICE_AND_BEANS,
	PET_SUPPLIES,
	PRODUCE,
	SNACKS_AND_SWEETS,
	SOUPS
}
