/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateEditPanel.java
 *
 * Created on Apr 24, 2011, 7:16:59 PM
 */

package com.customfit.ctg.view;

/**
 * Any panel that serves as a dual-purpose
 * Create and Edit view. Used to change
 * any dialog needed to discriminate view
 * type, including whether to ask the data
 * driver how to write the output model.
 * 
 * @author David
 */
public class CreateEditPanel extends SubPanel {

    /** Creates new form CreateEditPanel */
    public CreateEditPanel() {
        initComponents();
    }
    
    /** Creates new form CreateEditPanel */
    public CreateEditPanel(CreateEditMode createEditMode) {
        initComponents();
        this.createEditMode = createEditMode;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    private CreateEditMode createEditMode = CreateEditMode.EDIT;

    public CreateEditMode getCreateEditMode() {
        return createEditMode;
    }

    public void setCreateEditMode(CreateEditMode createEditMode) {
        this.createEditMode = createEditMode;
    }
}
