package com.customfit.ctg.view.users;

import com.customfit.ctg.controller.*;
import com.customfit.ctg.model.*;
import com.customfit.ctg.view.*;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;

/**
 * Presents the user a way to manage account settings.
 * 
 * @author David
 */
public class EditProfilePanel extends CreateEditPanel {

    /**
     * The user currently displayed on the panel.
     */
    private User user;
    
    /** Creates new form OldEditAccountPanel */
    public EditProfilePanel(CreateEditMode createEditMode) {
        initComponents();
        
        this.setCreateEditMode(createEditMode);
        
        if (createEditMode == CreateEditMode.CREATE)
        {
            this.jLabelTitle.setText("Register a New User");
            this.jTextPane1.setText("Please complete the following information in order to register a new user.\n\n" +  this.jTextPane1.getText());
            this.jButtonSave.setText("Register User");
            this.linkLabelDelete.setVisible(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDirection = new javax.swing.ButtonGroup();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        linkLabelDelete = new com.customfit.ctg.view.LinkLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonMaximumDirection = new javax.swing.JRadioButton();
        jRadioButtonMinimumDirection = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        scrollPaneIngedients = new javax.swing.JScrollPane();
        jTableMembers = new javax.swing.JTable();
        jButtonAddMember = new javax.swing.JButton();
        jButtonRemoveMember = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTargetAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTargetNutrient = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabelTitle.setText("Edit Profile");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Name:");

        jTextFieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUserKeyReleased(evt);
            }
        });

        jButtonSave.setText("Save Profile");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        linkLabelDelete.setText("I want to delete my user account.");
        linkLabelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLabelDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Would you like to scale your weekly menu based on a maximum or minimum nutritional amount?");

        buttonGroupDirection.add(jRadioButtonMaximumDirection);
        jRadioButtonMaximumDirection.setText("Maximum Amount");
        jRadioButtonMaximumDirection.setActionCommand("Maximum");

        buttonGroupDirection.add(jRadioButtonMinimumDirection);
        jRadioButtonMinimumDirection.setText("Minimum Amount");
        jRadioButtonMinimumDirection.setActionCommand("Minimum");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional members to track", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member", "Target Amount Per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMembers.getTableHeader().setReorderingAllowed(false);
        scrollPaneIngedients.setViewportView(jTableMembers);

        jButtonAddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/export/add-item.png"))); // NOI18N
        jButtonAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMemberActionPerformed(evt);
            }
        });

        jButtonRemoveMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art/export/subtract-item.png"))); // NOI18N
        jButtonRemoveMember.setDefaultCapable(false);
        jButtonRemoveMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoveMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
            .addComponent(scrollPaneIngedients, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRemoveMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneIngedients, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Target Nutrient:");

        jTextFieldTargetAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTargetAmountKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Target Amount Per Day:");

        jComboBoxTargetNutrient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Calories", "Fat", "Sodium" }));

        jScrollPane2.setBorder(null);

        jTextPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("control"));
        jTextPane1.setBorder(null);
        jTextPane1.setEditable(false);
        jTextPane1.setText("Please enter your name and your nutritional goals. You may specify a minimum goal or a maximum goal.  This will affect your meal portioning sizes and other calculations.");
        jTextPane1.setFocusable(false);
        jTextPane1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextPane1.setOpaque(false);
        jTextPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(522, 522, 522))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButtonMaximumDirection)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMinimumDirection)))
                        .addContainerGap(465, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(558, 558, 558))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxTargetNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTargetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(430, 430, 430))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(363, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMaximumDirection)
                    .addComponent(jRadioButtonMinimumDirection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTargetNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTargetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel)
                    .addComponent(linkLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUserKeyReleased
        //if user name is longer than two characters
        if (this.jTextFieldUser.getText().length() > 2)
        {
            //now check and see that the data is dirty
            if (this.user != null && this.jTextFieldUser.getText().equals(this.user.getName()))
                //disable sign up if it isn't
                this.jButtonSave.setEnabled(false);
            else
                //otherwise permit registration
                this.jButtonSave.setEnabled(true);
        }
        //otherwise
        else
            //disable sign up
            this.jButtonSave.setEnabled(false);
}//GEN-LAST:event_jTextFieldUserKeyReleased

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (this.getCreateEditMode() == CreateEditMode.EDIT)
        {
            //keep the previous user name
            String previousUserName = this.user.getName();
            //update the user
            this.user.setName(this.jTextFieldUser.getText());
            //update user and present previous panel
            UserManagement.updateRegistrationAndGoBack(previousUserName, this.user);
        }
        else if (this.getCreateEditMode() == CreateEditMode.CREATE)
        {
            //register user and present login
            UserManagement.registerUserAndPresentLogin(this.getUser());
        }
}//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //user bailed out, go back to the last panel
        Application.getMainFrame().goBack();
}//GEN-LAST:event_jButtonCancelActionPerformed

    private void linkLabelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLabelDeleteActionPerformed
        //tell controller to process delete request
        UserManagement.deleteUser(this.user.getName());
    }//GEN-LAST:event_linkLabelDeleteActionPerformed

    private void jButtonAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMemberActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTableMembers.getModel();
        dtm.addRow(new Object [] {null, null, null});
        jTableMembers.setModel(dtm);
}//GEN-LAST:event_jButtonAddMemberActionPerformed

    private void jButtonRemoveMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveMemberActionPerformed
        int currentRow = jTableMembers.getSelectedRow();
        if (currentRow != -1) {
            DefaultTableModel dtm = (DefaultTableModel)jTableMembers.getModel();
            dtm.removeRow(currentRow);

            jTableMembers.setModel(dtm);
            if (currentRow < jTableMembers.getRowCount())
                jTableMembers.setRowSelectionInterval(currentRow, currentRow);
        }
}//GEN-LAST:event_jButtonRemoveMemberActionPerformed

    private void jTextFieldTargetAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTargetAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTargetAmountKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDirection;
    private javax.swing.JButton jButtonAddMember;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRemoveMember;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxTargetNutrient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonMaximumDirection;
    private javax.swing.JRadioButton jRadioButtonMinimumDirection;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMembers;
    private javax.swing.JTextField jTextFieldTargetAmount;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextPane jTextPane1;
    private com.customfit.ctg.view.LinkLabel linkLabelDelete;
    private javax.swing.JScrollPane scrollPaneIngedients;
    // End of variables declaration//GEN-END:variables

    /**
     * Extends SubPanel functionality by returning the title as being the
     * same as on the panel itself.
     * @return The title in the panel.
     */
    @Override
    public String getTitle()
    {
        //grab title from on the panel
        return this.jLabelTitle.getText();
    }
    
    /**
     * Sets the User for which the form will be laid out.
     * @param user 
     */
    public void setUser(User user) {
        //store user in here
        this.user = user;
        //fill out form with current user data
        this.jTextFieldUser.setText(user.getName());
    }
    
    /**
     * Sets the User for which the form will be laid out.
     * @param user 
     */
    public User getUser()
    {
        NutritionFacts nutritionGoals = NutritionFacts.EmptyNutritionFacts;
        ArrayList<Member> members = new ArrayList<Member>();
        {
            //run this for the user itself
            String memberName = this.jTextFieldUser.getText();
            Double amount = Double.parseDouble(this.jTextFieldTargetAmount.getText());
            Measurement goal = new Measurement(amount, (String)jComboBoxTargetNutrient.getSelectedItem());
            GoalDirection goalDirection = GoalDirection.MAXIMUM_GOAL;
            if (this.buttonGroupDirection.getSelection().getActionCommand().equals("Maximum"))
                members.add(new Member(memberName, goal, GoalDirection.MAXIMUM_GOAL));
            else if (this.buttonGroupDirection.getSelection().getActionCommand().equals("Minimum"))
                members.add(new Member(memberName, goal, GoalDirection.MAXIMUM_GOAL));
        }
        for (int memberRow = 0; memberRow < this.jTableMembers.getModel().getRowCount(); memberRow++)
        {
            //run this for all the members
            String memberName = (String)this.jTableMembers.getModel().getValueAt(memberRow, 0);
            Double amount = (Double)this.jTableMembers.getModel().getValueAt(memberRow, 1);
            Measurement goal = new Measurement(amount, (String)jComboBoxTargetNutrient.getSelectedItem());
            GoalDirection goalDirection = GoalDirection.MAXIMUM_GOAL;
            ButtonModel model = (ButtonModel)this.buttonGroupDirection.getSelection();
            if (model.getActionCommand().equals("Maximum"))
                members.add(new Member(memberName, goal, GoalDirection.MAXIMUM_GOAL));
            else if (model.getActionCommand().equals("Minimum"))
                members.add(new Member(memberName, goal, GoalDirection.MAXIMUM_GOAL));
        }
        if (this.getCreateEditMode() == CreateEditMode.CREATE)
            return new User(
                    this.jTextFieldUser.getText(),
                    members,
                    new ArrayList<Meal>()
                    );
        else if (this.getCreateEditMode() == CreateEditMode.EDIT)
            return new User(
                    this.jTextFieldUser.getText(),
                    members,
                    this.user.getMeals()
                    );
        else
            return null;
    }
}
