/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIManageRecipesPanel.java
 *
 * Created on Apr 20, 2011, 8:45:16 PM
 */

package com.customfit.ctg.view.recipes;

import com.customfit.ctg.controllers.Application;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.customfit.ctg.view.GUIFormats;
import com.customfit.ctg.view.Observer;
import com.customfit.ctg.view.meal.GUIManageMenuPanel;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * This is the main panel for managing the recipes that are available
 * to select from.
 *
 * @author Ryan Spoon
 */
public class GUIManageRecipesPanel extends JPanel implements Observer {
    private Application controller;

    /** Creates new form GUIManageRecipesPanel */
    public GUIManageRecipesPanel(Application controller) {
        this.controller = controller;

        initComponents();
        custInitialize();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        panelSouth = new javax.swing.JPanel();
        btnMealMenu = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        scrollPaneTable = new javax.swing.JScrollPane();
        tblRecipes = new javax.swing.JTable();
        panelTableSouth = new javax.swing.JPanel();
        btnAddRecipe = new javax.swing.JButton();
        btnEditRecipe = new javax.swing.JButton();
        btnRemoveRecipe = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Recipe Box");
        add(lblTitle, java.awt.BorderLayout.PAGE_START);

        btnMealMenu.setText("Meal Menu");
        panelSouth.add(btnMealMenu);

        add(panelSouth, java.awt.BorderLayout.SOUTH);

        panelCenter.setLayout(new java.awt.BorderLayout());

        tblRecipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecipes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRecipes.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(tblRecipes);

        panelCenter.add(scrollPaneTable, java.awt.BorderLayout.CENTER);

        btnAddRecipe.setText("Add Recipe");
        panelTableSouth.add(btnAddRecipe);

        btnEditRecipe.setText("Edit Recipe");
        panelTableSouth.add(btnEditRecipe);

        btnRemoveRecipe.setText("Remove Recipe");
        panelTableSouth.add(btnRemoveRecipe);

        panelCenter.add(panelTableSouth, java.awt.BorderLayout.SOUTH);

        add(panelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void custInitialize() {
        GUIListener gl = new GUIListener();
        btnMealMenu.addActionListener(gl);
        btnAddRecipe.addActionListener(gl);
        btnEditRecipe.addActionListener(gl);
        btnRemoveRecipe.addActionListener(gl);


        lblTitle.setFont(GUIFormats.getTitleFont());
    }

    /**
     * Listener for this button panel.
     * Commands should be sent to the Controller
     * @author Ryan Spoon
     *
     */
    private class GUIListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae) {
            if(ae.getSource().equals(btnMealMenu)){
                controller.openPanel(new GUIManageMenuPanel(controller));
            }
            else if(ae.getSource().equals(btnAddRecipe))
            {
                controller.openPanel(new GUIEditRecipePanel(controller));
            }
            else if(ae.getSource().equals(btnEditRecipe))
            {
                GUIEditRecipePanel erp = new GUIEditRecipePanel(controller);
                //erp.setRecipe(controller.getRecipe(ID));
                controller.openPanel(erp);
            }
            else if(ae.getSource().equals(btnRemoveRecipe))
            {
                updateRecipeList();
            }
            else{
                // Shouldn't be here
            }
        }
    } // end private inner class

    private void updateRecipeList() {
        DefaultTableModel dtm = (DefaultTableModel)tblRecipes.getModel();

        Object[] o = {"hey", 4};
        dtm.addRow(o);
        tblRecipes.setModel(dtm);
        this.update();
    }

    /**
     * The update method refreshes this panel's data.
     */
    @Override
    public void update() {
            this.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecipe;
    private javax.swing.JButton btnEditRecipe;
    private javax.swing.JButton btnMealMenu;
    private javax.swing.JButton btnRemoveRecipe;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JPanel panelTableSouth;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTable tblRecipes;
    // End of variables declaration//GEN-END:variables

}
